name: tembo_core
description: Tembo UI SDK By TemboPlus
version: 0.0.1
homepage: https://github.com/okellogerald/tembo_core

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  url_launcher: ^6.1.12
  flex_color_scheme: ^7.0.5
  freezed_annotation: ^2.2.0
  flutter_riverpod: ^2.3.6
  hive: ^2.2.3
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.8
  linked_scroll_controller: ^0.2.0
  http: ^1.2.0
  uuid: ^4.4.0
  mixpanel_flutter: ^2.3.1

  firebase_dynamic_links: ^5.4.8
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/fonts/
